# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class App:
        name: str
        stage: str
    class MyLinkableValue:
        foo: str
        type: str
    class PythonFn:
        name: str
        type: str
        url: str
    class PythonFnCustom:
        name: str
        type: str
        url: str

