/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MyService": {
      "service": string
      "type": "sst.aws.Service"
    }
    "MyVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
