#!/bin/bash

ORIGINAL_DIR=$(pwd)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
echo "moving to $SCRIPT_DIR"
cd $SCRIPT_DIR

bun build ./functions/cf-static-site-router-worker/index.ts --target=node --outdir ./dist/cf-static-site-router-worker/
bun build ./functions/cf-ssr-site-router-worker/index.ts --target=node --outdir ./dist/cf-ssr-site-router-worker/
bun build ./functions/nodejs-runtime/index.ts --target=node --outdir ./dist/nodejs-runtime/
bun build ./functions/nodejs-runtime/loop.ts --target=node --outdir ./dist/nodejs-runtime/
GOARCH=amd64 GOOS=linux go build -o ./dist/bridge/bootstrap ./functions/bridge
node ./scripts/build.mjs

mkdir -p ./dist/python-runtime/
cp ./functions/python-runtime/index.py ./dist/python-runtime/index.py

mkdir -p ./dist/dockerfiles/
cp ./functions/docker/python.Dockerfile ./dist/dockerfiles/python.Dockerfile

cd ./support/bridge-task
timestamp=$(date +%Y%m%d%H%M%S)
docker build -t ghcr.io/sst/sst/bridge-task:$timestamp -t ghcr.io/sst/sst/bridge-task:latest .

if [ "$DOCKER_PUSH" = "true" ]; then
  docker push ghcr.io/sst/sst/bridge-task -a
fi


cd $ORIGINAL_DIR
